version: "3.8"
services:
    csc.node:
      image: node:12-alpine
      working_dir: /app
      env_file: .env
      volumes:
        - ./:/app
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
      command: sh -c "npm install && npm run build"
      restart: "no"
    csc.nginx:
      build:
        context: .
        dockerfile: ./docker/nginx.Dockerfile
      restart: always
      env_file: .env
      depends_on:
        - csc.node
      expose:
        - "${EXPOSE_PORT}"
      environment:
        VIRTUAL_HOST: "${VIRTUAL_HOST}"
      networks:
        - reverse-proxy
        - default
      volumes:
        - ./:/app/:ro
networks:
  reverse-proxy:
    external: true
